Repository OutDecision/OutDecision_Server, pull requests merged in 2024-05, with the labels that each got.

#80 ✨[FEAT]: 포인트랭킹 API 구현 (Redis)
  src/main/java/KGUcapstone/OutDecision/domain/ranking/controller/RankingRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/dto/RankingResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RankingService.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Title.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/TitleRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberRepository.java
  src/main/resources/application.yml
Labels: ✨FEAT

#83 🎨 [UPDATE]: 메인페이지 API 수정
  src/main/java/KGUcapstone/OutDecision/domain/main/dto/MainResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RankingService.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
Labels: 🎨Update

#84 [FEAT]: ci/cd
  Dockerfile
  build.gradle
Labels: ✨FEAT

#85 [FEAT]: ci/cd
  build.gradle
Labels: ✨FEAT

#86 [FEAT]: test CI/CD
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
Labels: ✨FEAT

#87 [FEAT]: ci/cd
  Dockerfile
Labels: 👷‍♂️CI

#88 [CI]: ci/cd
  src/main/resources/application-oauth.yml
Labels: 👷‍♂️CI

#89 [CI]: ci/cd
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/resources/templates/login.html
Labels: 👷‍♂️CI

#90 [CI]: ci/cd
  Dockerfile
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/resources/application-oauth.yml
Labels: 👷‍♂️CI

#91 [CI]: ci/cd
  Dockerfile
Labels: 👷‍♂️CI

#92 [CI]: ci/cd
  Dockerfile
Labels: 👷‍♂️CI

#93 [CI]: ci/cd
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/resources/templates/login.html
Labels: 👷‍♂️CI

#94 [CI]: ci/cd
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/resources/templates/login.html
Labels: 👷‍♂️CI

#95 [CI]: ci/cd
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/resources/templates/login.html
Labels: 👷‍♂️CI

#99 [UPDATE]: 로그인/회원가입
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/OAuth2Attribute.java
  src/main/resources/application-oauth.yml
  src/main/resources/templates/login.html
Labels: 🎨Update

#100 👷‍♂️ [CI]: ci/cd
  .github/workflows/gradle.yml
  Dockerfile
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationFailureHandler.java
Labels: 👷‍♂️CI

#101 🎨 [UPDATE]: multipartfile null 조건 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
Labels: 🎨Update

#102 🎨[Update] 추천시스템
  src/main/java/KGUcapstone/OutDecision/domain/main/dto/MainResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/RecommendSystem.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/UserBasedCF.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/MemberView.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberViewRepository.java
Labels: 🎨Update

#105 [BUG]: 통신 버그 수정
  src/main/java/KGUcapstone/OutDecision/global/config/security/WebConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
Labels: 🚑Bug Fix

#106 [BUG]: 통신 버그 수정
  src/main/java/KGUcapstone/OutDecision/global/config/security/WebConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
Labels: 🚑Bug Fix

#107 [BUGFIX]: CORS 오류
  src/main/java/KGUcapstone/OutDecision/global/config/security/WebConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
Labels: 🚑Bug Fix

#110 [BUGFIX]: 토큰 확인 오류
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
Labels: 🚑Bug Fix

#113 [UPDATE]: 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#114 [UPDATE]: 로그인한 사용자 id 찾기
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/FindMemberService.java
Labels: 🎨Update

#118 [BUGFIX]: recommendPost 오류 수정
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
Labels: 🚑Bug Fix

#120 [UPDATE]: 게시판 조회 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
Labels: 🎨Update

#122 [FEAT]: 회원 탈퇴 및 비밀번호 찾기 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/InquiryController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/LoginController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/RegisterController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/RevokeController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/InquiryRequestDto.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/InquiryResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/FindMemberService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/RevokeService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/help/InquiryService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/help/InquiryServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/ProjectBeanConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
  src/main/resources/templates/test.html
Labels: ✨FEAT

#124 [UPDATE]: 회원탈퇴 수정
  .github/workflows/gradle.yml
  Dockerfile
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/RevokeService.java
Labels: 🎨Update

#125 [UPDATE]: 게시판 조회 dto 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDTO.java
Labels: 🎨Update

#126 ✨[FEAT]: 게시글 작성, 삭제, 수정, 조회 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/comments/repository/CommentsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/options/repository/OptionsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/error/exception/handler/PostHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
  src/main/java/KGUcapstone/OutDecision/global/util/DateTimeFormatUtil.java
Labels: ✨FEAT

#128 ♻️ [REFACTOR]: 서비스에 @Transactional 붙이기
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/RevokeService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/SaveTokenService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/duplication/DuplicationServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/help/InquiryServiceImpl.java
Labels: ♻Refacotring

#130 🎨 [UPDATE}: 회원가입 - 칭호 미션 빌드해주기
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/ProjectBeanConfig.java
Labels: 🎨Update

#131 ✨[FEAT]: 투표 api 구현
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Missions.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Title.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/MissionsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/FindMemberService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/controller/VoteController.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteService.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteServiceImpl.java
Labels: ✨FEAT

#135 ✨ [FEAT]: 게시글 알림 엔티티 구현
  src/main/java/KGUcapstone/OutDecision/domain/notifications/domain/Notifications.java
Labels: ✨FEAT

#136 🎨 [UPDATE]: 알림 매핑 설정
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#132 ✨ [FEAT]: 댓글 작성, 삭제, API 구현
  src/main/java/KGUcapstone/OutDecision/domain/comments/controller/CommentsApiController.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsRequestDto.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/repository/CommentsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/service/CommentsService.java
Labels: ✨FEAT

#138 [FEAT]: 좋아요 api 구현
  src/main/java/KGUcapstone/OutDecision/domain/likes/controller/LikesController.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/service/LikesService.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/service/LikesServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/TtestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/repository/VoteRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteServiceImpl.java
Labels: ✨FEAT

#139 [FEAT]: 좋아요 api 구현
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: ✨FEAT

#144 [FEAT]: 좋아요 api 구현
  src/main/java/KGUcapstone/OutDecision/domain/likes/controller/LikesController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/TtestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteServiceImpl.java
Labels: ✨FEAT

#145 🎨 [UPDATE]: 게시글 작성 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#151 🎨 [UPDATE]: enum 소문자로 변경
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostsController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Category.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Gender.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
Labels: 🎨Update

#152 🎨 [UPDATE]: status enum 변경
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Status.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
Labels: 🎨Update

#153 🎨 [UPDATE]: 게시글 컬럼 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
Labels: 🎨Update

#155 [UPDATE]: 게시판 조회 수정
  src/main/java/KGUcapstone/OutDecision/domain/likes/repository/LikesRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/repository/NotificationsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostsController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Missions.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/repository/VoteRepository.java
Labels: 🎨Update

#156 ♻️ [REFACT]: 코드 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
Labels: ♻Refacotring

#157 ♻️ [REFACTOR]: 코드 수정
  src/main/java/KGUcapstone/OutDecision/domain/notifications/repository/NotificationsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: ♻Refacotring

#159 [UPDATE]: 포인트 획득 추가
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#160 ✨ [FEAT]: 끌어올리기
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: ✨FEAT

#166 ♻️ [REFACTOR]: findLoginMember() 사용하는 코드로 리팩
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/repository/NotificationsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/service/NotificationService.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/service/NotificationServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyActivityService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyActivityServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/error/exception/handler/MemberHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
Labels: ♻Refacotring

#167 🎨 [UPDATE]: 마이페이지&메인 끌어올리기 시간순 정렬로 변경
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyActivityServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageServiceImpl.java
Labels: 🎨Update

#163 ✨ [FEAT]: 끌어올리기
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: ✨FEAT

#171 🎨 [UPDATE]: 포인트랭킹 수정
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/LoginController.java
Labels: 🎨Update

#172 🎨 [UPDATE]: 포인트랭킹-개인랭크 공동순위 코드 수정
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
Labels: 🎨Update

#174 🎨 [UPDATE]: 게시판 조회 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
Labels: 🎨Update

#178 🎨 [UPDATE]: Cors 설정
  src/main/java/KGUcapstone/OutDecision/global/config/security/WebConfig.java
Labels: 🎨Update

#191 🐞 [BUGFIX]: 게시판 조회 오류 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostsController.java
Labels: 🚑Bug Fix

#192 🎨 [UPDATE]: 댓글 조회 최신순 정렬
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#194 🎨 [UPDATE]: 댓글 조회 프사 Response에 보내기
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
Labels: 🎨Update

#200 [UPDATE]: 로그인 쿠키 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/LoginController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/RevokeController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TokenController.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/CookieUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomLoginSuccessHandler.java
Labels: 🎨Update

#201 🎨 [UPDATE]: 게시글 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#202 🎨 [UPDATE]: 게시글 수정-사진 삭제 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#203 [UPDATE]: 로그인 쿠키 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TokenController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/CookieUtil.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomLoginSuccessHandler.java
Labels: 🎨Update

#204 [UPDATE]: 로그인 쿠키 수정
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomLoginSuccessHandler.java
Labels: 🎨Update

#207 Issue/197
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
Labels: 🎨Update

#212 🎨 [UPDATE]: 게시글 수정-파라미터값 변경
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#181 [REFACTOR]: 마이페이지 메인 홈
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageServiceImpl.java
Labels: ♻Refacotring

#217 🎨 [UPDATE]: 게시글 수정 api 최종변경
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
Labels: 🎨Update

#219 🐞 [BUGFIX]: 동시접속 에러 해결
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
Labels: :lady_beetle: Bug Fix

#223 🎨 [UPDATE]: 게시글 수정 복구
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#224 🎨 [UPDATE]: 임시 코드 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#225 🎨 [UPDATE]: 게시글 수정 오류 해결
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#226 [UPDATE]: 투표하기 수정
  src/main/java/KGUcapstone/OutDecision/domain/vote/controller/VoteController.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteService.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteServiceImpl.java
Labels: 🎨Update

#227 🎨 [UPDATE]: 댓글 조회 정렬 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#228 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/common/util/CookieUtil.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
Labels: :lady_beetle: Bug Fix

#229 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
Labels: :lady_beetle: Bug Fix

#230 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
Labels: :lady_beetle: Bug Fix

#231 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
Labels: :lady_beetle: Bug Fix

#232 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
Labels: :lady_beetle: Bug Fix

#233 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
Labels: :lady_beetle: Bug Fix

#234 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
Labels: :lady_beetle: Bug Fix

#235 [BUGFIX]: 동시접속 에러
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
Labels: :lady_beetle: Bug Fix

#238 🎨 [UPDATE]: 댓글 작성 수정
  src/main/java/KGUcapstone/OutDecision/domain/comments/controller/CommentsApiController.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
Labels: 🎨Update

#243 🎨 [UPDATE]: 좋아요 response 수정
  src/main/java/KGUcapstone/OutDecision/domain/likes/controller/LikesController.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/service/LikesService.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/service/LikesServiceImpl.java
Labels: 🎨Update

#245 🎨 [UPDATE]: 이메일 알림 핸들러 추가
  src/main/java/KGUcapstone/OutDecision/domain/notifications/service/NotificationServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/error/exception/handler/NotificationHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
Labels: 🎨Update

#249 🎨 [UPDATE]: 게시글 조회 변경-memberView 추가 및 댓글 작성여부 추가
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/MissionsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberViewRepository.java
Labels: 🎨Update

#241 🎨 [UPDATE]: 투표 수정
  src/main/java/KGUcapstone/OutDecision/domain/vote/controller/VoteController.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/dto/VoteResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteService.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/VoteServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/error/exception/handler/OptionHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
Labels: 🎨Update

#239 🎨 [UPDATE]: 로그인 후 사용자 정보 전달
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/LoginController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/MemberResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/FindMemberService.java
Labels: 🎨Update

#251 🎨 [UPDATE]: 게시글 삭제 오류 해결
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
Labels: 🎨Update

#253 🎨 [UPDATE]: 댓글 작성 수정
  src/main/java/KGUcapstone/OutDecision/domain/comments/controller/CommentsApiController.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/converter/CommentsConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/service/CommentsService.java
Labels: 🎨Update

#255 🎨 [UPDATE]: 게시글 조회 댓글ID 추가
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#257 🎨 [UPDATE]: 댓글id 이름 수정
  src/main/java/KGUcapstone/OutDecision/domain/comments/converter/CommentsConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
Labels: 🎨Update

#183 ♻️ [REFACTOR]: 마이페이지 칭호 변경
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
Labels: ♻Refacotring

#187 ♻️ [REFACTOR]: 마이페이지 프사 삭제
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgServiceImpl.java
Labels: ♻Refacotring

#189 ♻️ [REFACTOR]: 마이페이지 칭호 조회
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
Labels: ♻Refacotring

#259 🐞 [BUGFIX]: 일반 회원가입 오류 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/RegisterController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/ProjectBeanConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationSuccessHandler.java
Labels: 🎨Update

#215 ♻️ [REFACTOR]: 마이페이지 개인정보수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MemberService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MemberServiceImpl.java
Labels: ♻Refacotring

#195 ♻️ [REFACTOR]: 마이페이지 프사 변경
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgServiceImpl.java
Labels: ♻Refacotring

#205 ♻️ [REFACTOR]: 마이페이지 비번 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordServiceImpl.java
Labels: ♻Refacotring

#262 🎨 [UPDATE]: 사진 사이즈 수정
  src/main/resources/application.yml
Labels: 🎨Update

#263 🎨 [UPDATE]: 사진 크기 수정
  src/main/resources/application.yml
Labels: 🎨Update

#264 🎨 [UPDATE]: 사진 크기 수정
  src/main/resources/application.yml
Labels: 🎨Update

#266 🎨 [UPDATE]: 칭호미션 수정 및 사진 사이즈 변경
  src/main/java/KGUcapstone/OutDecision/domain/title/controller/MissionsRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsService.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
  src/main/resources/application.yml
Labels: 🎨Update

#268 🎨 [UPDATE]: 끌올 메소드 변경
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostRestController.java
Labels: 🎨Update

#269 🎨 [UPDATE]: 끌어올리기 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#270 🐞 [BUGFIX]: 엑세스토큰 시간 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomLoginSuccessHandler.java
Labels: :lady_beetle: Bug Fix

#272 🎨 [UPDATE]: 칭호 데이터 보내기
  src/main/java/KGUcapstone/OutDecision/domain/comments/converter/CommentsConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/comments/dto/CommentsResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#273 🎨 [UPDATE]: 프사 업로드 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgServiceImpl.java
Labels: 🎨Update

#274 🎨 [UPDATE]: 칭호 이모지 추가
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/TitleRepository.java
Labels: 🎨Update

#275 🎨 [UPDATE]: 칭호 사장 이모지 변경
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/TitleRepository.java
Labels: 🎨Update

#276 🎨 [UPDATE]: 랭킹 칭호 넘기기
  src/main/java/KGUcapstone/OutDecision/domain/ranking/dto/RankingResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/TitleRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
Labels: 🎨Update

#277 🎨 [UPDATE]: 칭호-랭킹 칭호 정보 전달
  src/main/java/KGUcapstone/OutDecision/domain/title/dto/MissionsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsService.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
Labels: 🎨Update

#278 🎨 [UPDATE]: 칭호-랭킹 칭호 정보 전달
  src/main/java/KGUcapstone/OutDecision/domain/title/dto/MissionsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsService.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
Labels: 🎨Update

#279 🎨 [UPDATE]: 칭호 빈문자열 에러 해결
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
Labels: 🎨Update
