Repository OutDecision/OutDecision_Server, pull requests merged in 2024-03, with the labels that each got.

#7 ✨[FEAT]: 엔티티 구현(사용자, 칭호)
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Title.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/User.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/enums/SocialType.java
  src/main/java/KGUcapstone/OutDecision/global/common/BaseEntity.java
Labels: ✨FEAT

#6 ✨ [FEAT]: 엔티티 구현(게시글, 좋아요)
  src/main/java/KGUcapstone/OutDecision/domain/Temp.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/domain/Likes.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Category.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Gender.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Status.java
Labels: ✨FEAT

#8 ✨ [FEAT]: 엔티티 구현(댓글, 투표, 투표옵션)
  src/main/java/KGUcapstone/OutDecision/domain/comments/domain/Comments.java
  src/main/java/KGUcapstone/OutDecision/domain/options/domain/Options.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/Vote.java
Labels: ✨FEAT

#10 [REFATORING]: 엔티티 클래스 명 변경 User->Member
  src/main/java/KGUcapstone/OutDecision/domain/comments/domain/Comments.java
  src/main/java/KGUcapstone/OutDecision/domain/likes/domain/Likes.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Title.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/Vote.java
Labels: ♻Refacotring

#12 ♻️ [REFACTOR]: Member 엔티티 컬럼 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: ♻Refacotring

#14 🎨 [UPDATE]: 사용자 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#18 🎨 [UPDATE]: 사용자 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/enums/SocialType.java
Labels: 🎨Update

#19 🎨 [UPDATE]: 사용자 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#20 🎨 [UPDATE]: 사용자 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update
