Repository OutDecision/OutDecision_Server, pull requests merged in 2024-04, with the labels that each got.

#28 🎨 [UPDATE]: 사용자 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#30 🐞 [BUG FIX]: 사용자 조회 기록 엔티티 오류 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/MemberView.java
Labels: 🚑Bug Fix

#31 ♻️ [REFACTOR]: 게시글 엔티티 매핑관계 추가
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
Labels: ♻Refacotring

#36 🎨 [UPDATE]: 사용자 엔티티 수정 - email
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: 🎨Update

#44 🎨 [UPDATE]: 칭호 엔티티 수정
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Title.java
Labels: 🎨Update

#46 ✨ [FEAT]: Redis 관련 세부 설정
  build.gradle
  src/main/java/KGUcapstone/OutDecision/OutDecisionApplication.java
  src/main/java/KGUcapstone/OutDecision/global/config/redis/RedisConfig.java
Labels: ✨FEAT

#50 ✨ [FEAT]: 투표연관옵션 엔티티 구현
  src/main/java/KGUcapstone/OutDecision/domain/options/domain/Options.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/Vote.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/VoteToOptions.java
Labels: ✨FEAT

#53 🎨 [UPDATE]: 엔티티 수정(post, likes)
  src/main/java/KGUcapstone/OutDecision/domain/likes/domain/Likes.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
Labels: 🎨Update

#55 ✨ [FEAT]: 칭호미션 엔티티 추가 및 다른 엔티티들 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Missions.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
Labels: ✨FEAT

#64 🎨 [UPDATE]: 엔티티 수정(게시글, 상태 enum)
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/enums/Category.java
Labels: 🎨Update

#61 ✨[FEAT]: 마이페이지 작성글&좋아요한 글&투표한 글 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/likes/repository/LikesRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/ActivityResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyActivityService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyActivityServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/repository/VoteRepository.java
Labels: ✨FEAT

#68 🎨 [UPDATE]: 마이페이지 개인정보수정 - 폰번호 수정 삭제
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/UpdateRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/UpdateResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MemberServiceImpl.java
Labels: 🎨Update

#62 ✨[FEAT]: 마이페이지 홈&칭호 변경 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/TitleRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/MemberResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/UpdateRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyPageService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyPageServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/TitleService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/TitleServiceImpl.java
Labels: ✨FEAT

#70 ✨ [FEAT]: 게시판 조회 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostsController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDto.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
Labels: ✨FEAT

#71 🎨 [UPDATE]: 마이페이지/게시판 API 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/controller/PostsController.java
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsService.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/MemberRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/ActivityResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/MemberResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyActivityServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/MyPageServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MemberService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MemberServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyActivityService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyActivityServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/TitleServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/UserImgServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/global/util/DateTimeFormatUtil.java
Labels: 🎨Update

#72 ✨[FEAT]: 메인 페이지 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/main/controller/MainRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/main/dto/MainResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainService.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
Labels: ✨FEAT

#39 ✨ [FEAT]: 로그인/회원가입 API 구현
  build.gradle
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/LoginController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/PageController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/RegisterController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TokenController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/CustomUserDetails.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/RefreshToken.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/RegisterRequestDto.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/TokenRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/FindMemberService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomOAuth2UserService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/CustomUserDetailsService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/OAuth2Attribute.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/SaveTokenService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
  src/main/java/KGUcapstone/OutDecision/global/common/properties/JwtProperties.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/AESUtil.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/CookieUtil.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
  src/main/java/KGUcapstone/OutDecision/global/config/redis/RedisConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/ProjectBeanConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/config/SecurityConfig.java
  src/main/java/KGUcapstone/OutDecision/global/security/dto/GeneratedToken.java
  src/main/java/KGUcapstone/OutDecision/global/security/dto/SecurityUserDto.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtAuthFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/filter/JwtExceptionFilter.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/KGUcapstone/OutDecision/global/security/handler/CustomLoginSuccessHandler.java
  src/main/resources/application-app.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/main/resources/templates/login-success.html
  src/main/resources/templates/login.html
  src/main/resources/templates/normal-register.html
  src/main/resources/templates/register-success.html
  src/main/resources/templates/social-register.html
Labels: ✨FEAT

#74 ✨[FEAT]: 칭호 미션 조회 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/title/controller/MissionsRestController.java
  src/main/java/KGUcapstone/OutDecision/domain/title/domain/Missions.java
  src/main/java/KGUcapstone/OutDecision/domain/title/dto/MissionsResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/title/repository/MissionsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsService.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberRepository.java
  src/main/java/KGUcapstone/OutDecision/global/error/handler/MemberHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
Labels: ✨FEAT

#75 🎨 [UPDATE]: 마이페이지 API 수정
  src/main/java/KGUcapstone/OutDecision/OutDecisionApplication.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/domain/Member.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/MemberResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/MyPageServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/user/util/BumpsReset.java
  src/main/java/KGUcapstone/OutDecision/global/error/handler/MemberHandler.java
  src/main/java/KGUcapstone/OutDecision/global/error/status/ErrorStatus.java
Labels: 🎨Update

#41 ✨ [FEAT]: 중복 검사 API 구현
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/DuplicationController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/DuplicationRequestDto.java
  src/main/java/KGUcapstone/OutDecision/domain/user/repository/MemberRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/duplication/DuplicationService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/duplication/DuplicationServiceImpl.java
Labels: ✨FEAT

#78 ♻️ [REFACT]: 투표 관련 엔티티 리팩토링
  src/main/java/KGUcapstone/OutDecision/domain/options/domain/Options.java
  src/main/java/KGUcapstone/OutDecision/domain/post/converter/PostConverter.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/Vote.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/domain/VoteToOptions.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/repository/VoteRepository.java
Labels: ♻Refacotring
