Repository OutDecision/OutDecision_Server, pull requests merged in 2024-06, with the labels that each got.

#282 🎨 [UPDATE]: 칭호 데이터 보내기
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#283 🎨 [UPDATE]: 칭호 데이터 보내기
  src/main/java/KGUcapstone/OutDecision/domain/post/dto/PostResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#284 🎨[UPDATE]: Main 페이지 수정
  src/main/java/KGUcapstone/OutDecision/domain/main/dto/MainResponseDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
Labels: 🎨Update

#285 🎨 [UPDATE]; 투표임박 정렬 수정
  src/main/java/KGUcapstone/OutDecision/domain/main/service/MainServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
Labels: 🎨Update

#289 🎨 [UPDATE]: 랭킹 칭호 수정
  src/main/java/KGUcapstone/OutDecision/domain/ranking/service/RedisRankingServiceImpl.java
Labels: 🎨Update

#137 ✨ [FEAT]: 투표 마감&이메일 알림
  build.gradle
  src/main/java/KGUcapstone/OutDecision/domain/notifications/repository/NotificationsRepository.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/service/NotificationService.java
  src/main/java/KGUcapstone/OutDecision/domain/notifications/service/NotificationServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/post/domain/Post.java
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/MailService.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/service/MailServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/vote/util/VoteClosingTask.java
  src/main/resources/application.yml
  src/main/resources/email-template-notification.txt
  src/main/resources/email-template.txt
Labels: ✨FEAT

#293 🎨 [UPDATE]: post 레포지토리에 추가
  src/main/java/KGUcapstone/OutDecision/domain/post/repository/PostRepository.java
Labels: 🎨Update

#297 [BUGFIX]: 동시접속 오류
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/TokenController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/auth/TokenService.java
Labels: :lady_beetle: Bug Fix

#298 [BUGFIX]: 동시접속 오류
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
Labels: :lady_beetle: Bug Fix

#300 ✨ [FEAT]: 비밀번호 재설정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/UpdateController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/UpdateRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordService.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordServiceImpl.java
Labels: ✨FEAT

#301 ✨ [FEAT]: 비밀번호 재설정
  src/main/java/KGUcapstone/OutDecision/domain/user/controller/UpdateController.java
  src/main/java/KGUcapstone/OutDecision/domain/user/dto/UpdateRequestDTO.java
  src/main/java/KGUcapstone/OutDecision/domain/user/service/mypage/PasswordServiceImpl.java
Labels: ✨FEAT

#302 🎨 [UPDATE]: 게시글 조회 시간 포맷 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
Labels: 🎨Update

#305 🎨 [UPDATE]: 칭호미션 수정
  src/main/java/KGUcapstone/OutDecision/domain/post/service/PostServiceImpl.java
  src/main/java/KGUcapstone/OutDecision/domain/title/service/MissionsServiceImpl.java
Labels: 🎨Update

#308 🐞 [BUGFIX]: 기본 프로필 이미지 삭제 오류 수정 및 토큰 시간 수정
  src/main/java/KGUcapstone/OutDecision/domain/user/service/S3Service.java
  src/main/java/KGUcapstone/OutDecision/global/common/util/JwtUtil.java
Labels: :lady_beetle: Bug Fix
